name: Slack Notifications

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Build, Scan"]
    types:
      - completed
  workflow_dispatch:

jobs:
  notify:
    uses: liatrio/github-workflows/.github/workflows/cve-slack-notifications.yaml@main
    with:
      image-name: ${{ github.event.repository.name }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_CVE_WORKFLOW_WEBHOOK }}
